//This code was generated by a tool.
//Changes to this file will be lost if the code is regenerated.
using SQLite;
using System;

namespace RedEmpleoOffLine
{
    public class SQLiteDb
    {
        string _path;
        public SQLiteDb(string path)
        {
            _path = path;
        }
        
         public void Create()
        {
            using (SQLiteConnection db = new SQLiteConnection(_path))
            {
                db.CreateTable<Departamento>();
                db.CreateTable<Municipio>();
                db.CreateTable<Personas>();
            }
        }
    }
    
    public partial class Departamento
    {
        [PrimaryKey]
        [Unique(Name = "departament_index", Order = 0)]
        [MaxLength(2)]
        public String IdCodigo { get; set; }
        [MaxLength(255)]
        [NotNull]
        public String nombre { get; set; }
    }
    public partial class Municipio
    {
        [PrimaryKey]
        [Unique(Name = "vacancy_codigomun", Order = 0)]
        [MaxLength(5)]
        public String IdCodigo { get; set; }
        [MaxLength(255)]
        [NotNull]
        public String nombre { get; set; }
        [MaxLength(2)]
        [NotNull]
        public String department_id { get; set; }
    }
    public partial class Personas
    {
        [PrimaryKey]
        [Unique(Name = "IX_Personas_Id", Order = 0)]
        public Int64 Id { get; set; }
        [MaxLength(50)]
        public String PrimerNombre { get; set; }
        [MaxLength(50)]
        [NotNull]
        public String SegundoNombre { get; set; }
        [MaxLength(50)]
        public String PrimerApellido { get; set; }
        [MaxLength(50)]
        [NotNull]
        public String SegundoApellido { get; set; }
        [MaxLength(2)]
        public String Sexo { get; set; }
        [MaxLength(10)]
        public String TipoDocumento { get; set; }
        [MaxLength(50)]
        public String NoDocumento { get; set; }
        [MaxLength(2147483647)]
        public String FechaNacimiento { get; set; }
        [MaxLength(50)]
        public String Usuario { get; set; }
        [MaxLength(50)]
        public String Contrasena { get; set; }
        [MaxLength(50)]
        public String Departamento { get; set; }
        [MaxLength(50)]
        public String Ciudad { get; set; }
        [MaxLength(50)]
        public String Direccion { get; set; }
        [MaxLength(50)]
        public String Barrio { get; set; }
        [MaxLength(50)]
        public String Telefono { get; set; }
        [MaxLength(50)]
        public String Celular { get; set; }
        [MaxLength(50)]
        public String CorreoElectronico { get; set; }
        [MaxLength(50)]
        public String CentroEmpleo { get; set; }
    }
}
