//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RedEmpleoOffLine.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personas
    {
        public long Id { get; set; }
        public string PrimerNombre { get; set; }
        public string SegundoNombre { get; set; }
        public string PrimerApellido { get; set; }
        public string SegundoApellido { get; set; }
        public string Sexo { get; set; }
        public string TipoDocumento { get; set; }
        public string NoDocumento { get; set; }
        public System.DateTime FechaNacimiento { get; set; }
        public string Usuario { get; set; }
        public string Contrasena { get; set; }
        public string Departamento { get; set; }
        public string Ciudad { get; set; }
        public string Direccion { get; set; }
        public string Barrio { get; set; }
        public string Telefono { get; set; }
        public string Celular { get; set; }
        public string CorreoElectronico { get; set; }
        public string CentroEmpleo { get; set; }
        public Nullable<bool> Estado { get; set; }
        public System.DateTime Fecha_Creacion { get; set; }
        public System.DateTime Fecha_Modificacion { get; set; }
        public Nullable<System.DateTime> Fecha_Sincronizacion { get; set; }
        public Nullable<bool> AllowEdit { get; set; }
    
        public virtual Municipio Municipio { get; set; }
    }
}
