//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RedEmpleoOffLine.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsuariosPuntos
    {
        public long Id { get; set; }
        public string Usuario { get; set; }
        public string Password { get; set; }
        public long RedempleoId { get; set; }
        public long Id_sedeRedempleo { get; set; }
        public string NombrePrestador { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public System.DateTime FechaModificacion { get; set; }
        public System.DateTime FechaIngreso { get; set; }
        public Nullable<System.DateTime> FechaSalida { get; set; }
    }
}
