//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RedEmpeloOffLine.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Municipio
    {
        public string IdCodigo { get; set; }
        public string nombre { get; set; }
        public string department_id { get; set; }
    
        public virtual Departamento Departamento { get; set; }
    }
}
